sudo: false
language: node_js
node_js:
- '7'
- '6'
- '5'
- '4'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run travis
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: Hhl3yTTUOBFr46vsoo2dlLn57kC8PRZlB9aRTFqywffb1y9oO1opH57LlPE2kDrhl3ZPCSrBqRArMuNmfGLPQeMxbya+QRZy0zHNoEGDS1HXIdv5FhWlt87ZZDJFqJS3xVS+HlqAzj7nEx1l3E3DLN+C/6yccHdmCP2SB+M8b9nTtCr18IDvaZoaAQ8j4o7SuBor9I+fUHlUH6QpdFuavUsTdCzEFvriFV9QZczHZ2wIsSmMEL/KzbgWKPJTZChS2fP/ivIR1/9YGkTrFhCe+SVyZhAix8F9O6eKTUmcj81sXAM+SnSPivSbQKm7aV84NoIGq2pY+MJdf089ar5II7wDELlkl48xiZWazuJK8P+98vdWglowerTNEQcIvB76CPOOsxRAJ21knbGHgnRh30ZhMq2gDeS9hYerlD0bWWJriHKlrQ8IfTxs76i3Yy4LYu+dO2DiCVYp0msJlGrucrsivAIZXnBoBWt36Lrca4DcnVBE9w5pf0UZmZbvsiwJZXOChwY7Q9t/uy3o3Ybxl3aB8l3AHDC7dairjnn2hpeRATK1ZyiR+MMEZzbOzW15Tfn8v6XuNafVLvpke6m8YcsXYTp5iMjgfMMKH6J/mtFdjvYrag+b01LQ646gcc1BssJPmyeJIUBeElPM+0mL7C3TWFyDlvSrLPR3nDuTgYg=
